// Mock novels data - used when backend API is unavailable
export const mockNovels = [
  {
    id: 1,
    title: 'ராட்சசனே என் வதைப்பதேனடா!',
    titleEnglish: 'Oh Demon! Why Do You Torment Me!',
    author: 'அமுது',
    authorEnglish: 'Amuthu',
    description: 'ஒரு பெண்ணின் வாழ்வில் வரும் கொடுமையான உலகத்தின் கதை',
    descriptionEnglish: 'A tale of a woman\'s journey through a harsh and cruel world',
    genre: 'drama',
    language: 'tamil',
    totalChapters: 14,
    image: 'Novel Card/Thenmozhi Card.jpg',
    coverImage: 'Novel Card/Thenmozhi Card.jpg',
    rating: 4.5,
    totalReviews: 150,
    slug: 'ratsasane-enai-vathaippathena',
    status: 'ongoing',
    views: 15000,
    createdAt: '2025-01-01',
    updatedAt: '2025-12-09'
  },
  {
    id: 2,
    title: 'தாலாட்டும் தாழம்பூவே!',
    titleEnglish: 'Lullaby of Temple Flower',
    author: 'அமுது',
    authorEnglish: 'Amuthu',
    description: 'ஒரு தாய்க்கும் மகளுக்கும் இடையிலான பிணைப்பு',
    descriptionEnglish: 'The bond between a mother and her daughter',
    genre: 'romance',
    language: 'tamil',
    totalChapters: 27,
    image: 'Novel Card/swetha card.jpg',
    coverImage: 'Novel Card/swetha card.jpg',
    rating: 4.3,
    totalReviews: 120,
    slug: 'thalattum-thazhampoove',
    status: 'ongoing',
    views: 12000,
    createdAt: '2025-01-05',
    updatedAt: '2025-12-08'
  },
  {
    id: 3,
    title: 'வந்தத்துணையே! என் வாழ்க்கைத் துணையே!',
    titleEnglish: 'Mohana',
    author: 'அமுது',
    authorEnglish: 'Mohanaamozhi',
    description: 'ஒரு கதையின் மூலம் கதை சொல்லப்படும் நாவல்',
    descriptionEnglish: 'A novel where a story is told through a story',
    genre: 'drama',
    language: 'tamil',
    totalChapters: 27,
    image: 'Novel Card/Mohana card.jpg',
    coverImage: 'Novel Card/Mohana card.jpg',
    rating: 4.2,
    totalReviews: 100,
    slug: 'mohana',
    status: 'ongoing',
    views: 10000,
    createdAt: '2025-01-10',
    updatedAt: '2025-12-07'
  }
];

export default mockNovels;
